server:
  port: 8080

spring:
  application:
    name: knowledge-qa
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.context.PropertyPlaceholderAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration